extensions:
    pim-family-create-modal:
       module: pim/form/common/creation-modal
       config:
           labels:
               title: pim_enrich.entity.family.create_popin.title
           successMessage: pim_enrich.entity.family.message.created
           innerForm: pim-family-create-form
           editRoute: pim_enrich_family_edit
           routerKey: code

    pim-family-create-form:
       module: pim/form/common/creation-code
       config:
          entity: family
          createRoute: pim_enrich_family_rest_create
